config/routes.rb
Rails.application.routes.draw do

  resources :cards
  resources :turnovers

  get 'welcome/index'

  match 'kundenuebersicht_part', to: "partners#kundenuebersicht", via: :all
  match 'limite_part', to: "partners#limite", via: :all

  resources :validations
  resources :terminations
  resources :service_turnovers
  resources :service_limits
  resources :sales_informations
  resources :return_debit_notes
  resources :pema_rents
  resources :payment_troubles
  resources :partner_roles
  resources :partners
  resources :motor_pools
  resources :liability_requests
  resources :invoices
  resources :fuel_turnovers
  resources :fuel_limits
  resources :fuel_cards
  resources :contacts
  resources :card_contracts

  resources :partners do
    resources :invoices
  end

  root 'welcome#index'

end

app/models/card_contract.rb
class CardContract < ActiveRecord::Base
  belongs_to :partner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_card.rb
class FuelCard < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_limit.rb
class FuelLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_turnover.rb
class FuelTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :partner
end

app/models/liability_request.rb
class LiabilityRequest < ActiveRecord::Base
  belongs_to :partner
end

app/models/motor_pool.rb
class MotorPool < ActiveRecord::Base
  belongs_to :partner
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  has_one :invoice
  accepts_nested_attributes_for :invoice

  has_one :contact
  accepts_nested_attributes_for :contact

  has_many :card_contracts
  has_many :fuel_cards
  has_many :fuel_limits
  has_many :fuel_turnovers
  has_many :liability_requests
  has_many :motor_pools
  has_many :partner_roles
  accepts_nested_attributes_for :partner_roles

  has_many :payment_troubles
  has_many :pema_rents
  has_many :return_debit_notes
  has_many :sales_informations
  has_many :service_limits
  has_many :service_turnovers
  has_many :terminations
  has_many :validations

end

app/models/partner_role.rb
class PartnerRole < ActiveRecord::Base
  belongs_to :partner
end

app/models/payment_trouble.rb
class PaymentTrouble < ActiveRecord::Base
  belongs_to :partner
end

app/models/pema_rent.rb
class PemaRent < ActiveRecord::Base
  belongs_to :partner
end

app/models/sales_information.rb
class SalesInformation < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_limit.rb
class ServiceLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_turnover.rb
class ServiceTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/termination.rb
class Termination < ActiveRecord::Base
  belongs_to :partner
end

app/models/validation.rb
class Validation < ActiveRecord::Base
  belongs_to :partner
end

app/controllers/sales_informations_controller.rb
class SalesInformationsController < ApplicationController
  before_action :set_sales_information, only: [:show, :edit, :update, :destroy]

  # GET /sales_informations
  # GET /sales_informations.json
  def index
    @sales_informations = SalesInformation.all
  end

  # GET /sales_informations/1
  # GET /sales_informations/1.json
  def show
  end

  # GET /sales_informations/new
  def new
    @sales_information = SalesInformation.new
  end

  # GET /sales_informations/1/edit
  def edit
  end

  # POST /sales_informations
  # POST /sales_informations.json
  def create
    @sales_information = SalesInformation.new(sales_information_params)

    respond_to do |format|
      if @sales_information.save
        format.html { redirect_to @sales_information, notice: 'Sales information was successfully created.' }
        format.json { render :show, status: :created, location: @sales_information }
      else
        format.html { render :new }
        format.json { render json: @sales_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_informations/1
  # PATCH/PUT /sales_informations/1.json
  def update
    respond_to do |format|
      if @sales_information.update(sales_information_params)
        format.html { redirect_to @sales_information, notice: 'Sales information was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_information }
      else
        format.html { render :edit }
        format.json { render json: @sales_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_informations/1
  # DELETE /sales_informations/1.json
  def destroy
    @sales_information.destroy
    respond_to do |format|
      format.html { redirect_to sales_informations_url, notice: 'Sales information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_information
      @sales_information = SalesInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_information_params
      params.require(:sales_information).permit(:partner_id, :berater_vorname, :berater_name, :kompetenzcenter, :niederlassung, :gueltig_bis, :gueltig_von)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/sales_informations_helper.rb
module SalesInformationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sales_informations/_form.html.haml
= simple_form_for(@sales_information) do |f|
  = f.error_notification

  .form-inputs
    = f.association :partner, :include_blank => false, :label_method => lambda { |partner| "#{partner.gevis_nummer}"}
    = f.input :berater_vorname
    = f.input :berater_name
    = f.input :kompetenzcenter
    = f.input :niederlassung
    = f.input :gueltig_bis
    = f.input :gueltig_von

  .form-actions
    = f.button :submit

app/views/sales_informations/edit.html.haml
%h1 Editing sales_information

= render 'form'

= link_to 'Show', @sales_information
\|
= link_to 'Back', sales_informations_path

app/views/sales_informations/index.html.haml
%h1 Listing sales_informations

%table
  %thead
    %tr
      %th Partner
      %th Berater vorname
      %th Berater name
      %th Kompetenzcenter
      %th Niederlassung
      %th Gueltig bis
      %th Gueltig von
      %th
      %th
      %th

  %tbody
    - @sales_informations.each do |sales_information|
      %tr
        %td= sales_information.partner
        %td= sales_information.berater_vorname
        %td= sales_information.berater_name
        %td= sales_information.kompetenzcenter
        %td= sales_information.niederlassung
        %td= sales_information.gueltig_bis
        %td= sales_information.gueltig_von
        %td= link_to 'Show', sales_information
        %td= link_to 'Edit', edit_sales_information_path(sales_information)
        %td= link_to 'Destroy', sales_information, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sales information', new_sales_information_path

app/views/sales_informations/new.html.haml
%h1 New sales_information

= render 'form'

= link_to 'Back', sales_informations_path

app/views/sales_informations/show.html.haml
%p#notice= notice

%p
  %b Partner:
  = @sales_information.partner
%p
  %b Berater vorname:
  = @sales_information.berater_vorname
%p
  %b Berater name:
  = @sales_information.berater_name
%p
  %b Kompetenzcenter:
  = @sales_information.kompetenzcenter
%p
  %b Niederlassung:
  = @sales_information.niederlassung
%p
  %b Gueltig bis:
  = @sales_information.gueltig_bis
%p
  %b Gueltig von:
  = @sales_information.gueltig_von

= link_to 'Edit', edit_sales_information_path(@sales_information)
\|
= link_to 'Back', sales_informations_path