config/routes.rb
Rails.application.routes.draw do

  resources :cards
  resources :turnovers

  get 'welcome/index'

  match 'kundenuebersicht_part', to: "partners#kundenuebersicht", via: :all
  match 'limite_part', to: "partners#limite", via: :all

  resources :validations
  resources :terminations
  resources :service_turnovers
  resources :service_limits
  resources :sales_informations
  resources :return_debit_notes
  resources :pema_rents
  resources :payment_troubles
  resources :partner_roles
  resources :partners
  resources :motor_pools
  resources :liability_requests
  resources :invoices
  resources :fuel_turnovers
  resources :fuel_limits
  resources :fuel_cards
  resources :contacts
  resources :card_contracts

  resources :partners do
    resources :invoices
  end

  root 'welcome#index'

end

app/models/card_contract.rb
class CardContract < ActiveRecord::Base
  belongs_to :partner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_card.rb
class FuelCard < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_limit.rb
class FuelLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_turnover.rb
class FuelTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :partner
end

app/models/liability_request.rb
class LiabilityRequest < ActiveRecord::Base
  belongs_to :partner
end

app/models/motor_pool.rb
class MotorPool < ActiveRecord::Base
  belongs_to :partner
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  has_one :invoice
  accepts_nested_attributes_for :invoice

  has_one :contact
  accepts_nested_attributes_for :contact

  has_many :card_contracts
  has_many :fuel_cards
  has_many :fuel_limits
  has_many :fuel_turnovers
  has_many :liability_requests
  has_many :motor_pools
  has_many :partner_roles
  accepts_nested_attributes_for :partner_roles

  has_many :payment_troubles
  has_many :pema_rents
  has_many :return_debit_notes
  has_many :sales_informations
  has_many :service_limits
  has_many :service_turnovers
  has_many :terminations
  has_many :validations

end

app/models/partner_role.rb
class PartnerRole < ActiveRecord::Base
  belongs_to :partner
end

app/models/payment_trouble.rb
class PaymentTrouble < ActiveRecord::Base
  belongs_to :partner
end

app/models/pema_rent.rb
class PemaRent < ActiveRecord::Base
  belongs_to :partner
end

app/models/return_debit_note.rb
class ReturnDebitNote < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_limit.rb
class ServiceLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_turnover.rb
class ServiceTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/termination.rb
class Termination < ActiveRecord::Base
  belongs_to :partner
end

app/models/validation.rb
class Validation < ActiveRecord::Base
  belongs_to :partner
end

app/controllers/pema_rents_controller.rb
class PemaRentsController < ApplicationController
  before_action :set_pema_rent, only: [:show, :edit, :update, :destroy]

  # GET /pema_rents
  # GET /pema_rents.json
  def index
    @pema_rents = PemaRent.all
  end

  # GET /pema_rents/1
  # GET /pema_rents/1.json
  def show
  end

  # GET /pema_rents/new
  def new
    @pema_rent = PemaRent.new
  end

  # GET /pema_rents/1/edit
  def edit
  end

  # POST /pema_rents
  # POST /pema_rents.json
  def create
    @pema_rent = PemaRent.new(pema_rent_params)

    respond_to do |format|
      if @pema_rent.save
        format.html { redirect_to @pema_rent, notice: 'Pema rent was successfully created.' }
        format.json { render :show, status: :created, location: @pema_rent }
      else
        format.html { render :new }
        format.json { render json: @pema_rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pema_rents/1
  # PATCH/PUT /pema_rents/1.json
  def update
    respond_to do |format|
      if @pema_rent.update(pema_rent_params)
        format.html { redirect_to @pema_rent, notice: 'Pema rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @pema_rent }
      else
        format.html { render :edit }
        format.json { render json: @pema_rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pema_rents/1
  # DELETE /pema_rents/1.json
  def destroy
    @pema_rent.destroy
    respond_to do |format|
      format.html { redirect_to pema_rents_url, notice: 'Pema rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pema_rent
      @pema_rent = PemaRent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pema_rent_params
      params.require(:pema_rent).permit(:partner_id, :vertragsnummer, :fahrgestellnummer, :laufzeit, :kaution, :status, :vertragsbeginn, :vertragsende, :zusatzinfos)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/pema_rents_helper.rb
module PemaRentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/pema_rents/_form.html.haml
= simple_form_for(@pema_rent) do |f|
  = f.error_notification

  .form-inputs
    = f.association :partner, :include_blank => false, :label_method => lambda { |partner| "#{partner.gevis_nummer}"}
    = f.input :vertragsnummer
    = f.input :fahrgestellnummer
    = f.input :laufzeit
    = f.input :kaution
    = f.input :status
    = f.input :vertragsbeginn
    = f.input :vertragsende
    = f.input :zusatzinfos

  .form-actions
    = f.button :submit

app/views/pema_rents/edit.html.haml
%h1 Editing pema_rent

= render 'form'

= link_to 'Show', @pema_rent
\|
= link_to 'Back', pema_rents_path

app/views/pema_rents/index.html.haml
%h1 Listing pema_rents

%table
  %thead
    %tr
      %th Partner
      %th Vertragsnummer
      %th Fahrgestellnummer
      %th Laufzeit
      %th Kaution
      %th Status
      %th Vertragsbeginn
      %th Vertragsende
      %th Zusatzinfos
      %th
      %th
      %th

  %tbody
    - @pema_rents.each do |pema_rent|
      %tr
        %td= pema_rent.partner
        %td= pema_rent.vertragsnummer
        %td= pema_rent.fahrgestellnummer
        %td= pema_rent.laufzeit
        %td= pema_rent.kaution
        %td= pema_rent.status
        %td= pema_rent.vertragsbeginn
        %td= pema_rent.vertragsende
        %td= pema_rent.zusatzinfos
        %td= link_to 'Show', pema_rent
        %td= link_to 'Edit', edit_pema_rent_path(pema_rent)
        %td= link_to 'Destroy', pema_rent, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pema rent', new_pema_rent_path

app/views/pema_rents/new.html.haml
%h1 New pema_rent

= render 'form'

= link_to 'Back', pema_rents_path

app/views/pema_rents/show.html.haml
%p#notice= notice

%p
  %b Partner:
  = @pema_rent.partner
%p
  %b Vertragsnummer:
  = @pema_rent.vertragsnummer
%p
  %b Fahrgestellnummer:
  = @pema_rent.fahrgestellnummer
%p
  %b Laufzeit:
  = @pema_rent.laufzeit
%p
  %b Kaution:
  = @pema_rent.kaution
%p
  %b Status:
  = @pema_rent.status
%p
  %b Vertragsbeginn:
  = @pema_rent.vertragsbeginn
%p
  %b Vertragsende:
  = @pema_rent.vertragsende
%p
  %b Zusatzinfos:
  = @pema_rent.zusatzinfos

= link_to 'Edit', edit_pema_rent_path(@pema_rent)
\|
= link_to 'Back', pema_rents_path