config/routes.rb
Rails.application.routes.draw do

  resources :cards
  resources :turnovers

  get 'welcome/index'

  match 'kundenuebersicht_part', to: "partners#kundenuebersicht", via: :all
  match 'limite_part', to: "partners#limite", via: :all

  resources :validations
  resources :terminations
  resources :service_turnovers
  resources :service_limits
  resources :sales_informations
  resources :return_debit_notes
  resources :pema_rents
  resources :payment_troubles
  resources :partner_roles
  resources :partners
  resources :motor_pools
  resources :liability_requests
  resources :invoices
  resources :fuel_turnovers
  resources :fuel_limits
  resources :fuel_cards
  resources :contacts
  resources :card_contracts

  resources :partners do
    resources :invoices
  end

  root 'welcome#index'

end

app/models/card_contract.rb
class CardContract < ActiveRecord::Base
  belongs_to :partner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_card.rb
class FuelCard < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_limit.rb
class FuelLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_turnover.rb
class FuelTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :partner
end

app/models/liability_request.rb
class LiabilityRequest < ActiveRecord::Base
  belongs_to :partner
end

app/models/motor_pool.rb
class MotorPool < ActiveRecord::Base
  belongs_to :partner
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  has_one :invoice
  accepts_nested_attributes_for :invoice

  has_one :contact
  accepts_nested_attributes_for :contact

  has_many :card_contracts
  has_many :fuel_cards
  has_many :fuel_limits
  has_many :fuel_turnovers
  has_many :liability_requests
  has_many :motor_pools
  has_many :partner_roles
  accepts_nested_attributes_for :partner_roles

  has_many :payment_troubles
  has_many :pema_rents
  has_many :return_debit_notes
  has_many :sales_informations
  has_many :service_limits
  has_many :service_turnovers
  has_many :terminations
  has_many :validations

end

app/models/partner_role.rb
class PartnerRole < ActiveRecord::Base
  belongs_to :partner
end

app/models/payment_trouble.rb
class PaymentTrouble < ActiveRecord::Base
  belongs_to :partner
end

app/models/pema_rent.rb
class PemaRent < ActiveRecord::Base
  belongs_to :partner
end

app/models/return_debit_note.rb
class ReturnDebitNote < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_limit.rb
class ServiceLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_turnover.rb
class ServiceTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/termination.rb
class Termination < ActiveRecord::Base
  belongs_to :partner
end

app/models/validation.rb
class Validation < ActiveRecord::Base
  belongs_to :partner
end

app/controllers/fuel_turnovers_controller.rb
class FuelTurnoversController < ApplicationController
  before_action :set_fuel_turnover, only: [:show, :edit, :update, :destroy]

  # GET /fuel_turnovers
  # GET /fuel_turnovers.json
  def index
    @fuel_turnovers = FuelTurnover.all
  end

  # GET /fuel_turnovers/1
  # GET /fuel_turnovers/1.json
  def show
  end

  # GET /fuel_turnovers/new
  def new
    @fuel_turnover = FuelTurnover.new
  end

  # GET /fuel_turnovers/1/edit
  def edit
  end

  # POST /fuel_turnovers
  # POST /fuel_turnovers.json
  def create
    @fuel_turnover = FuelTurnover.new(fuel_turnover_params)

    respond_to do |format|
      if @fuel_turnover.save
        format.html { redirect_to @fuel_turnover, notice: 'Fuel turnover was successfully created.' }
        format.json { render :show, status: :created, location: @fuel_turnover }
      else
        format.html { render :new }
        format.json { render json: @fuel_turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuel_turnovers/1
  # PATCH/PUT /fuel_turnovers/1.json
  def update
    respond_to do |format|
      if @fuel_turnover.update(fuel_turnover_params)
        format.html { redirect_to @fuel_turnover, notice: 'Fuel turnover was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuel_turnover }
      else
        format.html { render :edit }
        format.json { render json: @fuel_turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_turnovers/1
  # DELETE /fuel_turnovers/1.json
  def destroy
    @fuel_turnover.destroy
    respond_to do |format|
      format.html { redirect_to fuel_turnovers_url, notice: 'Fuel turnover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel_turnover
      @fuel_turnover = FuelTurnover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuel_turnover_params
      params.require(:fuel_turnover).permit(:dkv_nummer, :partner_id, :beschreibung, :belegdatum, :betrag, :waehrung, :rechnungsdruck)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/fuel_turnovers_helper.rb
module FuelTurnoversHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fuel_turnovers/_form.html.haml
= simple_form_for(@fuel_turnover) do |f|
  = f.error_notification

  .form-inputs
    = f.input :dkv_nummer
    = f.association :partner, :include_blank => false, :label_method => lambda { |partner| "#{partner.gevis_nummer}"}
    = f.input :beschreibung
    = f.input :belegdatum
    = f.input :betrag
    = f.input :waehrung
    = f.input :rechnungsdruck

  .form-actions
    = f.button :submit

app/views/fuel_turnovers/edit.html.haml
%h1 Editing fuel_turnover

= render 'form'

= link_to 'Show', @fuel_turnover
\|
= link_to 'Back', fuel_turnovers_path

app/views/fuel_turnovers/index.html.haml
%h1 Listing fuel_turnovers

%table
  %thead
    %tr
      %th Dkv nummer
      %th Partner
      %th Beschreibung
      %th Belegdatum
      %th Betrag
      %th Waehrung
      %th Rechnungsdruck
      %th
      %th
      %th

  %tbody
    - @fuel_turnovers.each do |fuel_turnover|
      %tr
        %td= fuel_turnover.dkv_nummer
        %td= fuel_turnover.partner
        %td= fuel_turnover.beschreibung
        %td= fuel_turnover.belegdatum
        %td= fuel_turnover.betrag
        %td= fuel_turnover.waehrung
        %td= fuel_turnover.rechnungsdruck
        %td= link_to 'Show', fuel_turnover
        %td= link_to 'Edit', edit_fuel_turnover_path(fuel_turnover)
        %td= link_to 'Destroy', fuel_turnover, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Fuel turnover', new_fuel_turnover_path

app/views/fuel_turnovers/new.html.haml
%h1 New fuel_turnover

= render 'form'

= link_to 'Back', fuel_turnovers_path

app/views/fuel_turnovers/show.html.haml
%p#notice= notice

%p
  %b Dkv nummer:
  = @fuel_turnover.dkv_nummer
%p
  %b Partner:
  = @fuel_turnover.partner
%p
  %b Beschreibung:
  = @fuel_turnover.beschreibung
%p
  %b Belegdatum:
  = @fuel_turnover.belegdatum
%p
  %b Betrag:
  = @fuel_turnover.betrag
%p
  %b Waehrung:
  = @fuel_turnover.waehrung
%p
  %b Rechnungsdruck:
  = @fuel_turnover.rechnungsdruck

= link_to 'Edit', edit_fuel_turnover_path(@fuel_turnover)
\|
= link_to 'Back', fuel_turnovers_path