config/routes.rb
Rails.application.routes.draw do

  resources :cards
  resources :turnovers

  get 'welcome/index'

  match 'kundenuebersicht_part', to: "partners#kundenuebersicht", via: :all
  match 'limite_part', to: "partners#limite", via: :all

  resources :validations
  resources :terminations
  resources :service_turnovers
  resources :service_limits
  resources :sales_informations
  resources :return_debit_notes
  resources :pema_rents
  resources :payment_troubles
  resources :partner_roles
  resources :partners
  resources :motor_pools
  resources :liability_requests
  resources :invoices
  resources :fuel_turnovers
  resources :fuel_limits
  resources :fuel_cards
  resources :contacts
  resources :card_contracts

  resources :partners do
    resources :invoices
  end

  root 'welcome#index'

end

app/models/card_contract.rb
class CardContract < ActiveRecord::Base
  belongs_to :partner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_card.rb
class FuelCard < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_limit.rb
class FuelLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/fuel_turnover.rb
class FuelTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :partner
end

app/models/liability_request.rb
class LiabilityRequest < ActiveRecord::Base
  belongs_to :partner
end

app/models/motor_pool.rb
class MotorPool < ActiveRecord::Base
  belongs_to :partner
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  has_one :invoice
  accepts_nested_attributes_for :invoice

  has_one :contact
  accepts_nested_attributes_for :contact

  has_many :card_contracts
  has_many :fuel_cards
  has_many :fuel_limits
  has_many :fuel_turnovers
  has_many :liability_requests
  has_many :motor_pools
  has_many :partner_roles
  accepts_nested_attributes_for :partner_roles

  has_many :payment_troubles
  has_many :pema_rents
  has_many :return_debit_notes
  has_many :sales_informations
  has_many :service_limits
  has_many :service_turnovers
  has_many :terminations
  has_many :validations

end

app/models/partner_role.rb
class PartnerRole < ActiveRecord::Base
  belongs_to :partner
end

app/models/payment_trouble.rb
class PaymentTrouble < ActiveRecord::Base
  belongs_to :partner
end

app/models/pema_rent.rb
class PemaRent < ActiveRecord::Base
  belongs_to :partner
end

app/models/return_debit_note.rb
class ReturnDebitNote < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_limit.rb
class ServiceLimit < ActiveRecord::Base
  belongs_to :partner
end

app/models/service_turnover.rb
class ServiceTurnover < ActiveRecord::Base
  belongs_to :partner
end

app/models/termination.rb
class Termination < ActiveRecord::Base
  belongs_to :partner
end

app/models/validation.rb
class Validation < ActiveRecord::Base
  belongs_to :partner
end

app/controllers/return_debit_notes_controller.rb
class ReturnDebitNotesController < ApplicationController
  before_action :set_return_debit_note, only: [:show, :edit, :update, :destroy]

  # GET /return_debit_notes
  # GET /return_debit_notes.json
  def index
    @return_debit_notes = ReturnDebitNote.all
  end

  # GET /return_debit_notes/1
  # GET /return_debit_notes/1.json
  def show
  end

  # GET /return_debit_notes/new
  def new
    @return_debit_note = ReturnDebitNote.new
  end

  # GET /return_debit_notes/1/edit
  def edit
  end

  # POST /return_debit_notes
  # POST /return_debit_notes.json
  def create
    @return_debit_note = ReturnDebitNote.new(return_debit_note_params)

    respond_to do |format|
      if @return_debit_note.save
        format.html { redirect_to @return_debit_note, notice: 'Return debit note was successfully created.' }
        format.json { render :show, status: :created, location: @return_debit_note }
      else
        format.html { render :new }
        format.json { render json: @return_debit_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /return_debit_notes/1
  # PATCH/PUT /return_debit_notes/1.json
  def update
    respond_to do |format|
      if @return_debit_note.update(return_debit_note_params)
        format.html { redirect_to @return_debit_note, notice: 'Return debit note was successfully updated.' }
        format.json { render :show, status: :ok, location: @return_debit_note }
      else
        format.html { render :edit }
        format.json { render json: @return_debit_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /return_debit_notes/1
  # DELETE /return_debit_notes/1.json
  def destroy
    @return_debit_note.destroy
    respond_to do |format|
      format.html { redirect_to return_debit_notes_url, notice: 'Return debit note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_return_debit_note
      @return_debit_note = ReturnDebitNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def return_debit_note_params
      params.require(:return_debit_note).permit(:partner_id, :eingang_rls, :grund, :faellig, :betrag, :ausgleich_rls, :rls_gebuehren, :tank_geschaeft, :dkv_informiert, :zahlungserinnerung, :mahnung1, :mahnung2, :zahlungseingang_datum, :zahlungseingang_betrag, :dkv_informiert2, :gueltig_bis)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/return_debit_notes_helper.rb
module ReturnDebitNotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/return_debit_notes/_form.html.haml
= simple_form_for(@return_debit_note) do |f|
  = f.error_notification

  .form-inputs
    = f.association :partner, :include_blank => false, :label_method => lambda { |partner| "#{partner.gevis_nummer}"}
    = f.input :eingang_rls
    = f.input :grund
    = f.input :faellig
    = f.input :betrag
    = f.input :ausgleich_rls
    = f.input :rls_gebuehren
    = f.input :tank_geschaeft
    = f.input :dkv_informiert
    = f.input :zahlungserinnerung
    = f.input :mahnung1
    = f.input :mahnung2
    = f.input :zahlungseingang_datum
    = f.input :zahlungseingang_betrag
    = f.input :dkv_informiert2
    = f.input :gueltig_bis

  .form-actions
    = f.button :submit

app/views/return_debit_notes/edit.html.haml
%h1 Editing return_debit_note

= render 'form'

= link_to 'Show', @return_debit_note
\|
= link_to 'Back', return_debit_notes_path

app/views/return_debit_notes/index.html.haml
%h1 Listing return_debit_notes

%table
  %thead
    %tr
      %th Partner
      %th Eingang rls
      %th Grund
      %th Faellig
      %th Betrag
      %th Ausgleich rls
      %th Rls gebuehren
      %th Tank geschaeft
      %th Dkv informiert
      %th Zahlungserinnerung
      %th Mahnung1
      %th Mahnung2
      %th Zahlungseingang datum
      %th Zahlungseingang betrag
      %th Dkv informiert2
      %th Gueltig bis
      %th
      %th
      %th

  %tbody
    - @return_debit_notes.each do |return_debit_note|
      %tr
        %td= return_debit_note.partner
        %td= return_debit_note.eingang_rls
        %td= return_debit_note.grund
        %td= return_debit_note.faellig
        %td= return_debit_note.betrag
        %td= return_debit_note.ausgleich_rls
        %td= return_debit_note.rls_gebuehren
        %td= return_debit_note.tank_geschaeft
        %td= return_debit_note.dkv_informiert
        %td= return_debit_note.zahlungserinnerung
        %td= return_debit_note.mahnung1
        %td= return_debit_note.mahnung2
        %td= return_debit_note.zahlungseingang_datum
        %td= return_debit_note.zahlungseingang_betrag
        %td= return_debit_note.dkv_informiert2
        %td= return_debit_note.gueltig_bis
        %td= link_to 'Show', return_debit_note
        %td= link_to 'Edit', edit_return_debit_note_path(return_debit_note)
        %td= link_to 'Destroy', return_debit_note, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Return debit note', new_return_debit_note_path

app/views/return_debit_notes/new.html.haml
%h1 New return_debit_note

= render 'form'

= link_to 'Back', return_debit_notes_path

app/views/return_debit_notes/show.html.haml
%p#notice= notice

%p
  %b Partner:
  = @return_debit_note.partner
%p
  %b Eingang rls:
  = @return_debit_note.eingang_rls
%p
  %b Grund:
  = @return_debit_note.grund
%p
  %b Faellig:
  = @return_debit_note.faellig
%p
  %b Betrag:
  = @return_debit_note.betrag
%p
  %b Ausgleich rls:
  = @return_debit_note.ausgleich_rls
%p
  %b Rls gebuehren:
  = @return_debit_note.rls_gebuehren
%p
  %b Tank geschaeft:
  = @return_debit_note.tank_geschaeft
%p
  %b Dkv informiert:
  = @return_debit_note.dkv_informiert
%p
  %b Zahlungserinnerung:
  = @return_debit_note.zahlungserinnerung
%p
  %b Mahnung1:
  = @return_debit_note.mahnung1
%p
  %b Mahnung2:
  = @return_debit_note.mahnung2
%p
  %b Zahlungseingang datum:
  = @return_debit_note.zahlungseingang_datum
%p
  %b Zahlungseingang betrag:
  = @return_debit_note.zahlungseingang_betrag
%p
  %b Dkv informiert2:
  = @return_debit_note.dkv_informiert2
%p
  %b Gueltig bis:
  = @return_debit_note.gueltig_bis

= link_to 'Edit', edit_return_debit_note_path(@return_debit_note)
\|
= link_to 'Back', return_debit_notes_path